services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
        - data:/data/db
        - config:/data/configdb
        - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: Passw0rd
        MONOG_INITDB_DATABASE: admin
    restart: always
volumes:
    data:
    config: